# Generated by Django 4.0.5 on 2022-08-09 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('midname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('father', models.CharField(max_length=200)),
                ('mother', models.CharField(max_length=200)),
                ('blood', models.CharField(max_length=3)),
                ('citizenshipno', models.CharField(max_length=50)),
                ('citizenshipdate', models.DateField()),
                ('citizenshipdistrict', models.CharField(max_length=200)),
                ('citizenship', models.ImageField(upload_to='')),
                ('zone', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=3)),
                ('tole', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.applicantinfo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.category')),
            ],
        ),
    ]
