# Generated by Django 4.0.5 on 2022-08-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/applicants'),
        ),
        migrations.AddField(
            model_name='license',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantinfo',
            name='citizenship',
            field=models.ImageField(blank=True, null=True, upload_to='media/citizenship'),
        ),
    ]
