# Generated by Django 4.0.5 on 2022-08-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_applicantinfo_photo_license_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantinfo',
            name='blood',
            field=models.CharField(choices=[('O', 'O'), ('A', 'A'), ('B', 'B'), ('AB', 'AB')], max_length=5),
        ),
    ]
